[default.extend-words]
soroban = "soroban"
Soroban = "Soroban"
Stellar = "Stellar"
XLM = "XLM"
mdbook = "mdbook"
WASM = "WASM"
wasm = "wasm"
Env = "Env"
Bytes = "Bytes"
BytesN = "BytesN"
require_auth = "require_auth"
symbol_short = "symbol_short"
Symbol = "Symbol"
Val = "Val"
Vec = "Vec"
Map = "Map"
WebAssembly = "WebAssembly"
Friendbot = "Friendbot"
Horizon = "Horizon"
RPC = "RPC"
SEP-41 = "SEP-41"
stroop = "stroop"
stroops = "stroops"
Ledger = "Ledger"
Testnet = "Testnet"
Mainnet = "Mainnet"
contractimpl = "contractimpl"
contracttype = "contracttype"
soroban-sdk = "soroban-sdk"
wasm-opt = "wasm-opt"
wasm32-unknown-unknown = "wasm32-unknown-unknown"

